--INITIALISATION TABLE MOVIE
INSERT INTO ACTOR(ACTOR_ID,NAME,RATING) VALUES (1,'brad pitt','4 stars');
INSERT INTO ACTOR(ACTOR_ID,NAME,RATING) VALUES (2,'Morgan Freeman','5 stars');

--INITIALISATION TABLE ACTOR
INSERT INTO MOVIE(MOVIE_ID,DESCRIPTION, DIRECTOR, NAME) values (1,'', 'Soderberg', 'Oceans eleven');
INSERT INTO MOVIE(MOVIE_ID,DESCRIPTION, DIRECTOR, NAME) values (2,'', 'Cameroon', 'Titanic');
INSERT INTO MOVIE(MOVIE_ID,DESCRIPTION, DIRECTOR, NAME) values (3,'', 'Tarantino', 'Once Upon a time');


insert into ACTOR_MOVIE(ACTOR_ID,MOVIE_ID) values(1,1);
insert into ACTOR_MOVIE(ACTOR_ID,MOVIE_ID) values(2,3);

